#!/bin/sh

files=$(git diff-index --name-only --cached HEAD -- '*.h' '*.cpp' '*.c' | \
	xargs clang-format -style=file --dry-run 2>&1 | wc -l)

if [ "$files" -ne 0 ]; then
	printf "Some files need to be formated with 'clang format'.\n" 1>&2
	exit 1
fi
